version: '2'
services:
    myapphip-app:
        image: myapphip
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://myapphip-mysql:3306/myapphip?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    myapphip-mysql:
        extends:
            file: mysql.yml
            service: myapphip-mysql
